name: 'LoadRunner Cloud Github Action - Run Test'
description: 'Start a test run in LoadRunner Cloud'
inputs:
  lrc_server:
    description: 'Server URL of LoadRunner Cloud'
    required: true
    default: 'https://loadrunner-cloud.saas.microfocus.com'
  lrc_tenant:
    description: 'Tenant ID of LoadRunner Cloud'
    required: true
  lrc_project:
    description: 'Project ID of LoadRunner Cloud'
    required: true
    default: '1'
  lrc_test_id:
    description: 'Test ID of LoadRunner Cloud'
    required: false
  lrc_output_dir:
    description: 'Path where you want to store the output files, like csv/pdf reports and so on.'
    required: false
    default: './'
  lrc_report_types:
    description: 'What type of reports should the action download, "csv", "pdf" and "docx" are supported. Use "," to separate multiple types.'
    required: false
    default: ''
outputs:
  lrc_run_id:
    description: 'Run ID of LoadRunner Cloud'
runs:
  using: 'node16'
  main: 'bundle/index.js'