name: 'GitHub Action for LoadRunner Cloud'
description: 'Run a test in LoadRunner Cloud'
inputs:
  lrc_server:
    description: 'LRC URL'
    required: true
    default: 'https://loadrunner-cloud.saas.microfocus.com'
  lrc_tenant:
    description: 'Tenant ID'
    required: true
  lrc_project:
    description: 'Project ID'
    required: true
    default: '1'
  lrc_test_id:
    description: 'Test ID'
    required: false
  lrc_output_dir:
    description: 'The directory to save results'
    required: false
    default: './'
  lrc_report_types:
    description: 'Target report types. For example: pdf, docx, csv'
    required: false
    default: ''
outputs:
  lrc_run_id:
    description: 'The ID of test run started by this action'
runs:
  using: 'node16'
  main: 'bundle/index.js'
