on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run LoadRunner test
        uses: ./ # Uses an action in the root directory
        id: lrc_run_test
      - name: Get the output runId
        run: echo "LRC Run ID is ${{ steps.lrc_run_test.outputs.lrc_run_id }}"
