on:
  workflow_dispatch:
    inputs:
      lrc_server:
        description: 'LRC URL'
        required: true
        default: 'https://loadrunner-cloud.saas.microfocus.com'
      lrc_tenant:
        description: 'Tenant ID'
        required: true
      lrc_project:
        description: 'Project ID'
        required: true
        default: '1'
      lrc_test_id:
        description: 'Test ID'
        required: true
      lrc_output_dir:
        description: 'The directory to save results'
        required: false
        default: './'
      lrc_report_types:
        description: 'Target report types. For example: pdf, docx, csv'
        required: false
        default: ''

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: Start a load test
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test in LoadRunner Cloud
        uses: ./ # Uses an action in the root directory
        id: lrc_run_test
        env:
          LRC_CLIENT_ID: ${{secrets.LRC_CLIENT_ID}}
          LRC_CLIENT_SECRET: ${{secrets.LRC_CLIENT_SECRET}}
        with:
          lrc_server: ${{ github.event.inputs.lrc_server }}
          lrc_tenant: ${{ github.event.inputs.lrc_tenant }}
          lrc_project: ${{ github.event.inputs.lrc_project }}
          lrc_test_id: ${{ github.event.inputs.lrc_test_id }}
          lrc_output_dir: ${{ github.event.inputs.lrc_output_dir }}
          lrc_report_types: ${{ github.event.inputs.lrc_report_types }}
      - name: Print test run ID
        run: echo "LRC Run ID is ${{ steps.lrc_run_test.outputs.lrc_run_id }}"
      - name: Upload LRC results
        uses: actions/upload-artifact@v3
        with:
          name: lrc-report-${{ steps.lrc_run_test.outputs.lrc_run_id }}
          path: ${{ github.event.inputs.lrc_output_dir }}
